# Generated by Django 3.1.1 on 2020-10-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='number',
            field=models.IntegerField(),
        ),
    ]
