# Generated by Django 3.1.1 on 2020-10-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20201016_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='number',
            field=models.TextField(max_length=25),
        ),
    ]
