# Generated by Django 3.1.1 on 2020-10-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_auto_20201021_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='number',
            field=models.CharField(max_length=25),
        ),
    ]
